logging:
  level: INFO
  loggers:
    de.justpegasus: DEBUG
path: /home/lutz/Music
defaultArtist: Arthur Artist
server:
  applicationConnectors:
    - type: http
      port: 8686
  adminConnectors:
    - type: http
      port: 8081
